services:
  mtunes:
    image: spice-tunes
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
       - .:/app
    working_dir: /app
    env_file:
      - ".env"
    ports:
      - "8000:8000"  # Adjust according to the port your app uses
    command: go run cmd/main.go
    

