name: Heroku Deploy

on:
  push:
    branches:
      - main # Changing the branch here would also work

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.13.15 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          stack: container
          usedocker: true
          docker_heroku_process_type: worker
        env:
          HD_SPICE_TUNES_DISCORD_TOKEN: ${{secrets.SPICE_TUNES_DISCORD_TOKEN}}
          HD_ENV: "PROD"
          HD_SPOTIFY_CLIENT_ID: ${{secrets.SPOTIFY_CLIENT_ID}}
          HD_SPOTIFY_CLIENT_SECRET: ${{secrets.SPOTIFY_CLIENT_SECRET}}
          HD_GCP_PROJECT_ID: ${{secrets.GCP_PROJECT_ID}}
          HD_GCP_PRIVATE_KEY_ID: ${{secrets.GCP_PRIVATE_KEY_ID}}
          HD_GCP_PRIVATE_KEY: ${{secrets.GCP_PRIVATE_KEY}}
          HD_GCP_CLIENT_EMAIL: ${{secrets.GCP_CLIENT_EMAIL}}
          HD_GCP_CLIENT_ID: ${{secrets.GCP_CLIENT_ID}}
          HD_YOUTUBE_USER_NAME: ${{secrets.YOUTUBE_USER_NAME}}
          HD_YOUTUBE_PASSWORD: ${{secrets.YOUTUBE_PASSWORD}}